# Generated by Django 4.2 on 2023-08-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.TextField()),
                ('payment_type', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('shipping_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('product_manufacture', models.TextField()),
                ('product_type', models.TextField()),
                ('product_model', models.TextField()),
                ('product_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_id', models.CharField(max_length=30)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartorder.cartorder')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
