# Generated by Django 4.1.11 on 2023-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='linkageid',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
