# Generated by Django 4.1.11 on 2023-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartorder', '0002_cartproduct_linkageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('result_code', models.CharField(max_length=10)),
                ('result_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('mpesa_receipt_number', models.TextField()),
                ('tranaction_date', models.TextField()),
                ('phonenumber', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='payment_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('response_code', models.CharField(max_length=10)),
                ('response_description', models.TextField()),
                ('customer_message', models.TextField()),
            ],
        ),
    ]
