# Generated by Django 4.1.11 on 2023-11-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartorder', '0003_payment_callback_payment_response'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment_callback',
            table='PaymentCallback',
        ),
        migrations.AlterModelTable(
            name='payment_response',
            table='PaymentResponse',
        ),
    ]
