# Generated by Django 4.1.11 on 2023-11-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartorder', '0004_alter_payment_callback_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_callback',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
    ]
