# Generated by Django 4.1.11 on 2023-11-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartorder', '0006_payment_callback_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_callback',
            name='order_id',
        ),
        migrations.AddField(
            model_name='payment_response',
            name='order_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
